config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#top_page"
  resources :users, only: [:edit, :update,:show] do
    collection do
      post 'update_attribute', to: 'users#update_attribute'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :tweets do
    resources :replies, only:[:create, :edit, :update, :destroy]
    collection do
      get 'top_page', to: 'tweets#top_page'
    end
  end
  # resources :teaches do
  #   resources :messages, only: [:create]
  #   namespace :api do
  #     resources :messages, only: :index, defaults: { format: 'json' }
  #   end
    
  # end
  resources :callrooms do
    collection do
      get 'update_attribute', to: 'callrooms#update_attribute'
      get :call
      post :cancelcall,defaults: { format: 'json' }
    end
    
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
  
  namespace :api do
    resources :callrooms, only: [:index, :new], defaults: { format: 'json' }
    resources :users, only: [:index, :new], defaults: { format: 'json' }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :replies, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:top_page, :index,:show]

  def top_page
    @tweets = Tweet.all.includes(:user).order("created_at DESC").limit(6)
    @callrooms = Callroom.where(status:1, student_id:nil).includes(:user).includes(:reviews).order("created_at DESC").limit(6)
  end

  def index
    @tweets = Tweet.all.includes(:user).order("created_at DESC").page(params[:page]).per(12)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet =Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @reply = Reply.new
    @replies = @tweet.replies.includes(:user)
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end
end


private
def tweet_params
  params.require(:tweet).permit(:title, :body, :image).merge(user_id: current_user.id)
end

app/views/tweets/_callroom.html.haml
.index-card
  -# 投稿者
  - if user_signed_in? && callroom.user_id == current_user.id
    = link_to callroom_path(callroom.id),class:"image-box" do
      - if callroom.image.present?
        = image_tag callroom.image.url,method: :get , class: 'index-image'
      - else 
        = image_tag(src= "/teacher.png", class: "index-image")

    = link_to callroom_path(callroom.id),class:"post-box" do
      %h3.title
        = callroom.title
      %h5.body
        = callroom.body

    -# 閲覧者
  - else
    .image-box{ class: "callroom-show", "data-show_id": "#{callroom.id}" }
      - if callroom.image.present?
        = image_tag callroom.image.url, class: 'index-image'
      - else 
        = image_tag(src= "/teacher.png", class: "index-image")

    .post-box{ class: "callroom-show", "data-show_id": "#{callroom.id}" }
      %h3.title
        = callroom.title
      %h5.body
        = callroom.body

  .profile-box
    = link_to user_path(callroom.user.id),method: :get, class: "profile-image-a"  do
      - if callroom.user.image.present? 
        = image_tag callroom.user.image.url, class: "profile-image"
      - else 
        = image_tag(src= "/no-image.png", class: "profile-image")
    = link_to user_path(callroom.user.id),method: :get  ,class: "profile-name" do
      = callroom.user.name
    = link_to user_path(callroom.user.id),method: :get  ,class: "post-created_at" do
      %small
        = callroom.created_at.strftime("%Y年%m月%d日")


// 生徒用先生詳細モーダル
%div{class:"call_info_modal" ,id:"modal-#{callroom.id}"}
  #call_info_modal_content
    .escape &times;
    .modal-profile-box
      = link_to user_path(callroom.user.id),method: :get, class: "modal-profile-image-a"  do
        - if callroom.user.image.present? 
          = image_tag callroom.user.image.url, class: "modal-profile-image"
        - else 
          = image_tag(src= "/no-image.png", class: "modal-profile-image")
      = link_to user_path(callroom.user.id),method: :get  ,class: "modal-profile-name" do
        #{callroom.user.name}さん
      = link_to user_path(callroom.user.id),method: :get  ,class: "modal-post-created_at" do
        = callroom.created_at.strftime("%Y年%m月%d日")
      - if user_signed_in?
        .btn-flat-vertical-border{ class: "call", "data-call_id": "#{callroom.id}" }
          電話する
      - else
        = link_to "電話する", callroom_path(callroom.id),method: :get,  class: "btn-flat-vertical-border"
    .modal-image-box
      - if callroom.image.present?
        = image_tag callroom.image.url, class: 'modal-index-image'
      - else 
        = image_tag(src= "/teacher.png", class: "modal-index-image")
    .modal-post-box
      %h3.modal-title
        = callroom.title
      %h5.modal-body
        = safe_join(callroom.body.split("\n"), tag(:br))
    -if callroom.reviews.present?
      .modal-review
        .review-average
          %div{ class:"rate", id:"modal-star-rate-#{callroom.id}"} 教えた人数#{callroom.reviews.count}人 &nbsp 平均:&nbsp#{callroom.reviews.average(:rate).to_f.round(2)} &nbsp/5&nbsp
          .btn-flat-vertical-border{class: "call", "data-call_id": "#{callroom.id}"} 
            電話する
        .modal-review-box
          ＜コメント一覧＞
          = render partial: '/tweets/review', collection: callroom.reviews, as: :review
    
:javascript
  $('#modal-star-rate-#{callroom.id}').raty({
  size: 36,
  starOff: "#{asset_path('star-off.png')}",
  starOn: "#{asset_path('star-on.png')}",
  starHalf: "#{asset_path('star-half.png')}",
  half: true,
  readOnly: true,
  //平均点を算出し、round関数で切り上げ
  score: "#{callroom.reviews.average(:rate).to_f.round(2)}",
  
  });

app/views/tweets/_form.html.haml
%dl
  .field
    .field-label
      = form.label :title, "題名"
      %span.must※
    .field-input
      = form.text_field :title,placeholder: "題名を入力してくだい(最大２０文字)",required: "",maxlength: "20"
  .field-image 
    .field-image-label
      = form.label :image, class:"form_image" do
        画像
        .preview-box
          -if @tweet.image.present?
            = image_tag @tweet.image.url, class: 'tweet_image'
          - else
            = image_tag(src= "/no-image.png", class: "tweet_image")
    = form.file_field :image, class: 'hidden'
  .field
    .field-label
      = form.label :body, "本文"
      %span.must※
    .field-input
      = form.text_area :body, placeholder:"勉強したことやわかったことをまとめよう", required: "" 
.actions
  = form.submit "投稿する", class: 'btn'

app/views/tweets/_main_tweet.html.haml
%ul.section-box
  %li.section
    = link_to "Output", tweets_path, method: :get, class:"title_logo"
  .index-box
    = render @tweets
  = link_to "もっと見る", tweets_path, method: :get, class:"btn btn--orange btn--cubic btn--shadow"

  %li.section
    = link_to "Call", callrooms_path, method: :get, class:"title_logo"
  .index-box
    = render partial: 'callroom', collection: @callrooms, as: :callroom
  = link_to "もっと見る", callrooms_path, method: :get, class:"btn btn--orange btn--cubic btn--shadow"

app/views/tweets/_reply.html.haml
.reply-list__box{data: {reply: {id: replies.id}}}
  .comment-author
    -# ユーザーの写真
    = link_to "#", class: "link-image"do
      - if replies.user.image.present?
        %p
          = image_tag replies.user.image.url, class: 'author__image'
      - else
        %P
          = image_tag(src= "/no-image.png", class: "author__image")

    -# 投稿者
    = link_to "#", class: "author__name" do
      = replies.user.name
      
    -# コメント
    - if replies.comment.present?
      %p.reply-list__box__comment
        = replies.comment
    = image_tag replies.image.url, class: 'lower-reply__image' if replies.image.present?

    -# 投稿日時
    .author__created_at
      = replies.created_at.strftime("%Y年%m月%d日%H時%M分")

app/views/tweets/_review.html.haml
-if review.comment.present?
  .modal-review-card
    .modal-reviewer.balloon_l 
      -if review.user.image.present?
        .faceicon
          = image_tag reviewe.image.url
      -else review.user.image.present?
        .faceicon
          .faceicon
          = image_tag(src= "/no-image.png")
      .says
        %p{ class:"rate modal-rate", id:"modal-star-reviewr-info-#{review.id}"} 
          #{review.rate}&nbsp/5&nbsp
        %p 
          = safe_join(review.comment.split("\n"), tag(:br))

:javascript
  $('#modal-star-reviewr-info-#{review.id}').raty({
  size: 36,
  starOff: "#{asset_path('star-off.png')}",
  starOn: "#{asset_path('star-on.png')}",
  starHalf: "#{asset_path('star-half.png')}",
  half: true,
  readOnly: true,
  //平均点を算出し、round関数で切り上げ
  score: "#{review.rate.to_f.round(1)}",
  
  });

app/views/tweets/_tweet.html.haml
= link_to tweet_path(tweet.id),method: :get , class:"index-card" do
  .image-box
    - if tweet.image.present?
      = image_tag tweet.image.url,method: :get , class: 'index-image'
    - else 
      = image_tag(src= "/study.webp", class: "index-image")

  .post-box
    %h3.title
      = tweet.title
    %h5.body
      = tweet.body

  .profile-box
    %object
      = link_to user_path(tweet.user.id),method: :get, class: "profile-image-a"  do
        - if tweet.user.image.present? 
          = image_tag tweet.user.image.url, class: "profile-image"
        - else 
          = image_tag(src= "/no-image.png", class: "profile-image")
    %object
      = link_to user_path(tweet.user.id),method: :get  ,class: "profile-name" do
        = tweet.user.name
    %object
      = link_to user_path(tweet.user.id),method: :get  ,class: "post-created_at" do
        %small
          = tweet.created_at.strftime("%Y年%m月%d日")

app/views/tweets/edit.html.haml
.wraper
  .container
    = form_for(@tweet) do |form|
      %h3 投稿する
      = render partial: "form", locals:{ form: form }

app/views/tweets/index.html.haml
.wraper
  .index-body
    .section
      Output
    .index-box
      = render @tweets
    = paginate(@tweets)

app/views/tweets/new.html.haml
.wraper
  .container
    = form_for(@tweet) do |form|
      %h3 投稿する
      = render partial: "form", locals:{ form: form }

app/views/tweets/show.html.haml
.show-body
  .author
    = link_to user_path(@tweet.user_id), class: "link-image"do
      - if @tweet.user.image.present?
        %p
          = image_tag @tweet.user.image.url, class: 'author__image'
      - else
        %P
          = image_tag(src= "/no-image.png", class: "author__image")
    = link_to user_path(@tweet.user_id), class: "author__name" do
      = @tweet.user.name
    
    .author__created_at
      = @tweet.created_at.strftime("%Y年%m月%d日")

    -if user_signed_in? && current_user.id == @tweet.user_id
      .manage
        = link_to edit_tweet_path(@tweet.id), class: "manage__edit" do
          = icon('far', 'edit')
          編集
        = link_to tweet_path(@tweet.id), method: :delete, class: "manage__destroy" do
          = icon("fa", "trash-alt")
          削除
  .tweet
    %h1.show-title
      = @tweet.title
    - if @tweet.image.present?
      %p
        = image_tag @tweet.image.url, class: 'tweet__image'

    .tweet__body
      = safe_join(@tweet.body.split("\n"), tag(:br))

  .show-form
    = form_for [@tweet, @reply] do |f|
      = f.text_field :comment, class: 'form__reply', placeholder: 'コメント'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          = icon('fas', 'image', class: 'icon')
          = f.file_field :image, class: 'hidden'
      - if user_signed_in?
        = f.submit 'コメントする', class: 'comment__submit'
      - else 
        = link_to  tweet_path(@tweet.id), method: :delete do
          %button.comment__submit コメントする
    %p.small Enterキーでも投稿します。
    
    .comment <コメント一覧>
    .reply-list
      = render partial: 'reply', collection: @replies, as: :replies

app/views/tweets/top_page.html.haml
.wraper
  .index-body
    = render "main_tweet"