config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#top_page"
  resources :users, only: [:edit, :update,:show] do
    collection do
      post 'update_attribute', to: 'users#update_attribute'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :tweets do
    resources :replies, only:[:create, :edit, :update, :destroy]
    collection do
      get 'top_page', to: 'tweets#top_page'
    end
  end
  # resources :teaches do
  #   resources :messages, only: [:create]
  #   namespace :api do
  #     resources :messages, only: :index, defaults: { format: 'json' }
  #   end
    
  # end
  resources :callrooms do
    collection do
      get 'update_attribute', to: 'callrooms#update_attribute'
      get :call
      post :cancelcall,defaults: { format: 'json' }
    end
    
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
  
  namespace :api do
    resources :callrooms, only: [:index, :new], defaults: { format: 'json' }
    resources :users, only: [:index, :new], defaults: { format: 'json' }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :tweets
  has_many :messages
  has_many :replies
  has_one :callroom
  has_many :reviews

  validates :name, presence: true, uniqueness: true, length: { maximum: 10,  message:"は10文字以下で登録してください" }

  # ゲストユーザー
  def self.guest
    find_or_create_by!(name: "ゲストユーザー",email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  # 新規登録及び編集時のUser.nameの一意制の確認
  def index
    # 新規ユーザーが名前を登録する際に名前がかぶっていないか検索する。
    unless user_signed_in?
      @user = User.find_by(name: params[:name])
      return @user
    end
    # 編集時に自分の名前を抜かしてが名前がかぶっていないか検索
    unless current_user.name == params[:name]
      @user = User.find_by(name: params[:name])
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save(user_params)
      sign_in(:user, @user)
      redirect_to root_path, notice:"アカウント登録が完了しました。"
    else
      render :new and return
    end
  end


  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def user_params
    params.require(:user).permit(:name, :email,:password, 
      :password_confirmation, :introduction, :subject, :image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_guest, only:[:edit]

  def edit
  end
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  # def update_attribute
  #   if current_user.called == false
  #     current_user.called = 1
  #     current_user.save
  #   else current_user.called == 1
  #     current_user.called = 0
  #     current_user.save
  #   end
  #   redirect_to root_path
  # end

  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: params[:id]).includes(:user).order("created_at DESC").limit(6)
    @user_callroom = Callroom.find_by(user_id: params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :image, :introduction, :subject, :email)
  end


  def check_guest
    email = current_user&.email || params[:user][:email].downcase
    if current_user.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは編集できません。'
    end
  end

end

app/views/users/edit.html.haml
= form_for(current_user) do |f|
  .user-sign_up-login-box
    %dl
      %h2 Edit Account
      %h5 アカウントの編集
      .ben
        = link_to "ログアウト",  destroy_user_session_path, method: :delete, class: 'new-user_login_btn'
        = link_to "トップページに戻る", :back, class: 'new-user_login_btn'
      .field
        .field-label
          = f.label :name, "名前"
          %span.must※
          .error_user_name
        .field-input
          = f.text_field :name,placeholder: "名前を入力してくだい", autofocus: true
      .field-image 
        .field-image-label
          = f.label :image, class:"form_image" do
            画像
            .preview-box
              - if current_user.image.present?
                = image_tag current_user.image.url, class: "tweet_image"
              - else
                = image_tag(src= "/no-image.png", class: "tweet_image")
          = f.file_field :image, class: 'hidden'
      .field
        .field-label
          = f.label :email, "メールアドレス"
          %span.must※
        .field-input
          = f.text_field :email, placeholder: "メールアドレスを入力してください", autofocus: true
      .field
        .field-label
          = f.label :introduction, "自己紹介文"
        .field-input
          = f.text_area :introduction, placeholder: "自己紹介文（電話するときに表示されます）", autofocus: true
      .field
        .field-label
          = f.label :subject, "好きな教科"
        .field-input
          = f.text_field :subject,placeholder: "好きな教科（数学、情報処理など）", autofocus: true
    .actions
      = f.submit "編集する", class: 'btn'

app/views/users/show.html.haml
.user-show-body
  .UserMainContainer
    .BaseContainerUserInfomation
      .author
        - if @user.image.present?
          = image_tag @user.image.url, class: 'author__image'
        - else
          = image_tag(src= "/no-image.png", class: "author__image")
      .account_name
        = @user.name
      .user_introduction
        - if @user.introduction.present?
          = safe_join(@user.introduction.split("\n"), tag(:br))
        - elsif user_signed_in? && @user.id ==  current_user.id
          自己紹介：未設定
      .user_favorite_subject
        - if @user.introduction.present?
          好きな教科：
          = (safe_join(@user.subject.split("\n"), tag(:br)))
        - elsif user_signed_in? && @user.id ==  current_user.id
          好きな教科：未設定
      - if user_signed_in? && current_user.id == @user.id
        .user_edit_button
          = link_to "プロフィールを編集する", edit_user_path(@user.id), class:"user_edit_button__link"
    .BaseContainer_user_post
      .user_post_header
        .user_post_header__mark
        .user_post_header__info 記事一覧
      %ul.userpost_tab
        %li{class:"userpost_tab_tweets active"}
          = link_to "アウトプット", "#tweets"
        %li.userpost_tab_callroom
          = link_to "電話用", "#callroom"

      %div{class:"tabContents active", id:"tweets"}
        最近の投稿
        .index-box
          = render partial: '/tweets/tweet', collection: @tweets, as: :tweet
      %div{class:"tabContents", id:"callroom"}
        電話用
        - if @user_callroom.present?
          - if @user_callroom.status == 0
            現在　非公開
          - elsif @user_callroom.status == 1
            現在　公開中
          - elsif @user_callroom.status == 2 or @user_callroom.status == 3
            現在　通信中
          .index-box
            = render partial: '/tweets/callroom', locals:{callroom: @user_callroom} 
        - else 
          現在　設定していません

  -#     -if user_signed_in? && current_user.id == @user_id
  -#       .manage
  -#         = link_to edit_tweet_path(@user.id), class: "manage__edit" do
  -#           = icon('far', 'edit')
  -#           編集
  -#         = link_to  tweet_path(@user.id), method: :delete, class: "manage__destroy" do
  -#           = icon("fa", "trash-alt")
  -#           削除
  -# .tweet
  -#   %h1.show-title
  -#     = @user.name
  -#   %h1.show-title
  -#     = @user.subject
  -#   - if @user.image.present?
  -#     %p
  -#       = image_tag @user.image.url, class: 'tweet__image'

  -#   .tweet__body
  -#     = safe_join(@user.introduction.split("\n"), tag(:br))

  -# .tweet
  -#   %h1.show-title
  -#     = @user.title
  -#   - if @user.image.present?
  -#     %p
  -#       = image_tag @user.image.url, class: 'tweet__image'

  -#   .tweet__body
  -#     = safe_join(@user.body.split("\n"), tag(:br))

  -# .show-form
  -#   = form_for [@user, @reply] do |f|
  -#     = f.text_field :comment, class: 'form__reply', placeholder: 'コメント'
  -#     .form__mask
  -#       = f.label :image, class: 'form__mask__image' do
  -#         = icon('fas', 'image', class: 'icon')
  -#         = f.file_field :image, class: 'hidden'
  -#     = f.submit 'コメントする', class: 'form__submit'
  -#   %p.small Enterキーで投稿します。
  -#   .comment <コメント一覧>
  -#   .reply-list
  -#     = render partial: 'reply', collection: @replies, as: :replies