config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "tweets#top_page"
  resources :users, only: [:edit, :update,:show] do
    collection do
      post 'update_attribute', to: 'users#update_attribute'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  resources :tweets do
    resources :replies, only:[:create, :edit, :update, :destroy]
    collection do
      get 'top_page', to: 'tweets#top_page'
    end
  end
  # resources :teaches do
  #   resources :messages, only: [:create]
  #   namespace :api do
  #     resources :messages, only: :index, defaults: { format: 'json' }
  #   end
    
  # end
  resources :callrooms do
    collection do
      get 'update_attribute', to: 'callrooms#update_attribute'
      get :call
      post :cancelcall,defaults: { format: 'json' }
    end
    
    resources :reviews, only: [:create]
    resources :messages, only: [:create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
  
  namespace :api do
    resources :callrooms, only: [:index, :new], defaults: { format: 'json' }
    resources :users, only: [:index, :new], defaults: { format: 'json' }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    = include_gon
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    -# なくてもよい
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"}
    %title StuSuppo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    
  %body
    = render 'layouts/notifications'
    %header
      .hyoji
        %h1.logo
          = link_to root_path, class:"logo-link" do
            stu
            %br
            　suppo
        .title
          = link_to root_path, class:"title-link" do
            study-support
        %ul.btn
          -if user_signed_in? 
            = link_to user_path(current_user), class:"btn__profile" do
              %li
                = current_user.name
            = link_to destroy_user_session_path, method: :delete, class:"btn__logout" do
              %li ログアウト
            = link_to new_tweet_path, method: :get, class:"btn__tweet" do
              %li アウトプット
              -# 電話ができるようにする。（編集モード）
            - if @callroom.present? && @callroom.status == 0 
              = link_to edit_callroom_path(@callroom.id), method: :get, class:"btn__teach" do
                %li 教えるモード(編集)
              -# 新しく電話ができないようにする。
            - elsif @callroom.nil?
              = link_to new_callroom_path, method: :get, class:"btn__teach" do
                %li 教えるモード
              -# 電話ができないようにする。
            - elsif @callroom.present? && @callroom.status == 1 or @callroom.status == 2 or @callroom.status == 3
              = link_to update_attribute_callrooms_path, method: :get, class:"btn__teach" do
                %li 教えるモード（非公開）
            
          -else
            = link_to new_user_registration_path, method: :get, class:"btn__logout" do
              %li 新規登録
            = link_to users_guest_sign_in_path, method: :post, class:"btn__tweet" do
              %li ゲストログイン
            = link_to  new_user_session_path, method: :get, class:"btn__tweet" do
              %li ログイン
    
    = yield
    #callmodal
      #callmodal_content
    #modal
      #modal_content